DROP TABLE IF EXISTS music_instrument;
CREATE SEQUENCE IF NOT EXISTS mi_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE music_instrument (
                      id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      type        VARCHAR(255)    NOT NULL,
                      brand       VARCHAR(255)    NOT NULL,
                      model       VARCHAR(255)    NOT NULL,
                      price       DOUBLE          NOT NULL,
                      stock       INT             NOT NULL
);