DROP TABLE IF EXISTS Item;
CREATE SEQUENCE IF NOT EXISTS item_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE Item (
                      id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      code        VARCHAR(6)      NOT NULL UNIQUE,
                      type        VARCHAR(255)    NOT NULL,
                      name        VARCHAR(255)    NOT NULL,
                      price       DOUBLE          NOT NULL,
                      item_count  INT             NOT NULL
);